// <auto-generated />
namespace MvcProva6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class alunoNovo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alunoNovo));
        
        string IMigrationMetadata.Id
        {
            get { return "202010072209008_alunoNovo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
